### ISSUE TITLE
Error in .env concerning docker hub repository name

### ISSUE THREAD

**Issue by gusperlee** [chalmers-revere/opendlv.miniature#35]
In .env and in the dockerfile in test.ps4controller in the dit168 branch the line 
`IMAGE_ARM=seresearch/2018-dit-168-dev:v0.3.5-armhf`
seems to be wrong, should it not be this instead?
`IMAGE_ARM=seresearch/2018-dit-168:v0.3.5-armhf`
The "-dev" part is not in any repository name that we could find.

**Comment by bjornborg** [comment]
ping @chrberger @fgiaimo 
Do you know more about this?

**Comment by fgiaimo** [comment]
Just a typo, it is fixed now.

**Comment by gusperlee** [comment]
Sorry, had a mix-up in the title of the issue, Dockerfile has the same typo as in .env:
`IMAGE_ARM=seresearch/2018-dit-168-dev:v0.3.5-armhf`
instead of
`IMAGE_ARM=seresearch/2018-dit-168:v0.3.5-armhf`

**Comment by fgiaimo** [comment]
Good observation. 
Having the image name in a variable in the .env file results in making the Dockerfile unnecessary. 
It will be deleted now.
